AWSTemplateFormatVersion: 2010-09-09
Description: App Tier for Star Wars Application which consists of an internal ALB

Resources:

  # Internal ALB for Web Tier
    SW{{ Environment }}{{ Region }}ALB:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        SecurityGroups: [{{ SWELBSGID }}]
        Scheme: internal
        Name : SW-{{ TagEnvironment }}-{{ TagRegion }}-ALB-internal
        Subnets:
          - {{ PrivateSubnet1 }}
          - {{ PrivateSubnet2 }}
        Tags:
          - Key: Name
            Value: SW-{{ TagEnvironment }}-{{ TagRegion }}-ALB-internal
          - Key: Tr:environment-type
            Value: {{ Environment_type }}
          - Key: Tr:project-name
            Value: Star Wars
          - Key: Tr:service-name
            Value: Web-App


###### Target Groups for App Servers


    SWApp{{ Environment }}{{ Region }}ALBTargetGroup1:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        HealthCheckIntervalSeconds: 60
        HealthCheckTimeoutSeconds: 5
        HealthyThresholdCount: 3
        Port: 9403
        Protocol: HTTP
        Name: SW-App-1-{{ TagEnvironment }}-{{ TagRegion }}-TG-Int
        UnhealthyThresholdCount: 5
        VpcId: {{ VpcId }}
        Targets:
          - Id: i-1234
          - Id: i-5678
          - Id: i-9101


  #ALB Listener
    SW{{ Environment }}{{ Region }}ALBListener1:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        DefaultActions:
          - Type: forward
            TargetGroupArn: !Ref SWApp{{ Environment }}{{ Region }}ALBTargetGroup1
        LoadBalancerArn: !Ref SW{{ Environment }}{{ Region }}ALB
        Port: 80
        Protocol: HTTP


######Listener Rules for App Servers

    ListenerRuleApp1:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
        Actions:
        - Type: forward
          TargetGroupArn:
            Ref: SWApp{{ Environment }}{{ Region }}ALBTargetGroup1
        Conditions:
        - Field: host-header
          Values:
          - "SW-service9-use1-aws.abc.com"
        ListenerArn:
          Ref: SW{{ Environment }}{{ Region }}ALBListener1
        Priority: 1
